#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Character.h"
#include "Actor/WeaponHolderInterface.h"
#include "Actor/WeaponActor.h"
#include "AbilitySystemInterface.h"
#include "FighterCharacter.generated.h"

class UAbilitySystemComponent;
class UAttributeSet;
class UGameplayEffect;

/// Characters can attack, be hurt, die as results of interactions by WeaponActor
/// in their hand socket belongs to their skeleton.
/// 
/// Stats are managed by AttributeSet which means their modification is conducted
/// by GameplayEffect based on attack damage attribute.
UCLASS(abstract)
class BEADURINC_API AFighterCharacter : public ACharacter, public IAbilitySystemInterface, public IWeaponHolderInterface
{
	GENERATED_BODY()
	
	/** Holding weapon class */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category="Equipments", meta = (AllowPrivateAccess = "true"))
	TSubclassOf<AWeaponActor> WeaponActorBlueprint;
	
protected:
	
	/** Gameplay Ability class for Hit React */
	UPROPERTY(EditDefaultsOnly, Category = "Gameplay Abilities")
	TSubclassOf<UGameplayAbility> HitReactAbility;
	
	/** Gameplay Ability System Component */
	UPROPERTY()
	TObjectPtr<UAbilitySystemComponent> AbilitySystemComponent;
	
	/** Gameplay Abilities Attribute Set */
	UPROPERTY()
	TObjectPtr<UAttributeSet> AttributeSet;
	
	/** Instance holder generated by WeaponActorBlueprint */
	UPROPERTY()
	TObjectPtr<AWeaponActor> WeaponActorInstance;
	
	/** List of Actors that hit by "current swing" */
	TSet<TObjectPtr<AActor>> HitActors;
	
protected:
	/** On character first join the world */
	virtual void BeginPlay() override;
	
	/** Called on the WeaponActor hits any actor when collision activated by anim notify state */
	UFUNCTION()
	virtual void OnMeleeContacts
	(
		UPrimitiveComponent* OverlappedComponent,
		AActor* OtherActor,
		UPrimitiveComponent* OtherComp,
		int32 OtherBodyIndex,
		bool bFromSweep,
		const FHitResult& SweepResult
	);
	
public:
	void ResetMeleeSwing();
	
	/** Returns whether the character is holding weapon in main hand **/
	FORCEINLINE virtual bool IsHoldingWeapon() const override { return IsValid(WeaponActorInstance); }

	/** Returns Equipping Weapon Actor in main hand **/
	FORCEINLINE virtual TObjectPtr<AWeaponActor> GetWeaponActor() const override { return WeaponActorInstance; }
	
	/** Returns Ability Component object **/
	FORCEINLINE virtual UAbilitySystemComponent* GetAbilitySystemComponent() const override { return AbilitySystemComponent; };
};
